Added edit decoders without save test
wazuh-fe-qa/wazuh-cypress pull request #65
Opened 2022-06-28 16:33 UTC by Mayons95

Added edit decoders without saving test

2022-06-28 17:16 UTC, mauceballos requested changes

2022-06-28 17:16 UTC, mauceballos commented on cypress/integration/features/management/decoders/edit-decoders-without-saving.feature
> +    Then The informative modal is displayed
add new line at en d the line

2022-06-28 17:16 UTC, mauceballos commented on cypress/integration/step-definitions/management/decoders/the-confirm-modal-is-displayed-then.js
> +});
add new line at en d the line

2022-06-28 17:16 UTC, mauceballos commented on cypress/integration/step-definitions/management/decoders/the-user-edit-the-selected-decoder-when.js
> +});
add new line at en d the line

2022-06-28 17:16 UTC, mauceballos commented on cypress/integration/step-definitions/management/decoders/the-user-exit-without-saving-decoder-when.js
> +});
add new line at en d the line

2022-06-28 17:16 UTC, mauceballos commented on cypress/integration/step-definitions/management/decoders/the-user-selects-a-custom-decoder-when.js
> +});
add new line at en d the line

2022-06-28 17:50 UTC, Mayons95 commented on cypress/integration/features/management/decoders/edit-decoders-without-saving.feature
> +    Then The informative modal is displayed
Done

2022-06-28 17:51 UTC, Mayons95 commented on cypress/integration/step-definitions/management/decoders/the-confirm-modal-is-displayed-then.js
> +});
Done

2022-06-28 17:51 UTC, Mayons95 commented on cypress/integration/step-definitions/management/decoders/the-user-edit-the-selected-decoder-when.js
> +});
Done

2022-06-28 17:51 UTC, Mayons95 commented on cypress/integration/step-definitions/management/decoders/the-user-exit-without-saving-decoder-when.js
> +});
Done

2022-06-28 17:52 UTC, Mayons95 commented on cypress/integration/step-definitions/management/decoders/the-user-selects-a-custom-decoder-when.js
> +});
Done

2022-06-29 13:03 UTC, mauceballos approved these changes

2022-06-29 13:03 UTC, merged