Fixes for rules test
wazuh-fe-qa/wazuh-cypress pull request #73
Opened 2022-06-29 15:47 UTC by Mayons95

2022-06-29 16:25 UTC, matiasmoreno876 approved these changes
LGYM

2022-06-29 18:10 UTC, mauceballos requested changes

2022-06-29 18:10 UTC, mauceballos commented on cypress/integration/features/management/decoders/edit-decoders-without-saving.feature
> +    Given The kibana admin user is logged and the wazuh logo is displayed
the step should be following this:
    Given The wazuh admin user is logged

2022-06-29 18:10 UTC, mauceballos commented on cypress/integration/features/management/rules/edit-rules-without-saving.feature
> +    Given The kibana admin user is logged and the wazuh logo is displayed
the step should be following this:
    Given The wazuh admin user is logged

2022-06-30 14:12 UTC, mauceballos approved these changes

2022-06-30 15:04 UTC, merged